/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedPassportRouteImport } from './routes/_authenticated/passport'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedAdventurersRouteImport } from './routes/_authenticated/adventurers'
import { Route as AuthenticatedStoryIdRouteImport } from './routes/_authenticated/story.$id'
import { Route as AuthenticatedPetsNewRouteImport } from './routes/_authenticated/pets.new'
import { Route as AuthenticatedAdventurersNewRouteImport } from './routes/_authenticated/adventurers.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassportRoute = AuthenticatedPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdventurersRoute =
  AuthenticatedAdventurersRouteImport.update({
    id: '/adventurers',
    path: '/adventurers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoryIdRoute = AuthenticatedStoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsNewRoute = AuthenticatedPetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdventurersNewRoute =
  AuthenticatedAdventurersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdventurersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/adventurers': typeof AuthenticatedAdventurersRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/adventurers/new': typeof AuthenticatedAdventurersNewRoute
  '/pets/new': typeof AuthenticatedPetsNewRoute
  '/story/$id': typeof AuthenticatedStoryIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/adventurers': typeof AuthenticatedAdventurersRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/': typeof AuthenticatedIndexRoute
  '/adventurers/new': typeof AuthenticatedAdventurersNewRoute
  '/pets/new': typeof AuthenticatedPetsNewRoute
  '/story/$id': typeof AuthenticatedStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/adventurers': typeof AuthenticatedAdventurersRouteWithChildren
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/passport': typeof AuthenticatedPassportRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/adventurers/new': typeof AuthenticatedAdventurersNewRoute
  '/_authenticated/pets/new': typeof AuthenticatedPetsNewRoute
  '/_authenticated/story/$id': typeof AuthenticatedStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/adventurers'
    | '/create'
    | '/library'
    | '/onboarding'
    | '/passport'
    | '/rewards'
    | '/settings'
    | '/subscription'
    | '/adventurers/new'
    | '/pets/new'
    | '/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/adventurers'
    | '/create'
    | '/library'
    | '/onboarding'
    | '/passport'
    | '/rewards'
    | '/settings'
    | '/subscription'
    | '/'
    | '/adventurers/new'
    | '/pets/new'
    | '/story/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/adventurers'
    | '/_authenticated/create'
    | '/_authenticated/library'
    | '/_authenticated/onboarding'
    | '/_authenticated/passport'
    | '/_authenticated/rewards'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/'
    | '/_authenticated/adventurers/new'
    | '/_authenticated/pets/new'
    | '/_authenticated/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passport': {
      id: '/_authenticated/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AuthenticatedPassportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adventurers': {
      id: '/_authenticated/adventurers'
      path: '/adventurers'
      fullPath: '/adventurers'
      preLoaderRoute: typeof AuthenticatedAdventurersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story/$id': {
      id: '/_authenticated/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof AuthenticatedStoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/new': {
      id: '/_authenticated/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof AuthenticatedPetsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adventurers/new': {
      id: '/_authenticated/adventurers/new'
      path: '/new'
      fullPath: '/adventurers/new'
      preLoaderRoute: typeof AuthenticatedAdventurersNewRouteImport
      parentRoute: typeof AuthenticatedAdventurersRoute
    }
  }
}

interface AuthenticatedAdventurersRouteChildren {
  AuthenticatedAdventurersNewRoute: typeof AuthenticatedAdventurersNewRoute
}

const AuthenticatedAdventurersRouteChildren: AuthenticatedAdventurersRouteChildren =
  {
    AuthenticatedAdventurersNewRoute: AuthenticatedAdventurersNewRoute,
  }

const AuthenticatedAdventurersRouteWithChildren =
  AuthenticatedAdventurersRoute._addFileChildren(
    AuthenticatedAdventurersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdventurersRoute: typeof AuthenticatedAdventurersRouteWithChildren
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPassportRoute: typeof AuthenticatedPassportRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPetsNewRoute: typeof AuthenticatedPetsNewRoute
  AuthenticatedStoryIdRoute: typeof AuthenticatedStoryIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdventurersRoute: AuthenticatedAdventurersRouteWithChildren,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPassportRoute: AuthenticatedPassportRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPetsNewRoute: AuthenticatedPetsNewRoute,
  AuthenticatedStoryIdRoute: AuthenticatedStoryIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
